export const MAINTENANCE_RESOURCE_TYPE = {
  ROOM: 'ROOM',
  PROJECTOR: 'PROJECTOR',
  SOUND_SYSTEM: 'SOUND_SYSTEM',
  AIR_CONDITIONER: 'AIR_CONDITIONER',
  SEAT: 'SEAT',
  QR_SCANNER: 'QR_SCANNER',
  POS: 'POS',
  EQUIPMENT_OTHER: 'EQUIPMENT_OTHER',
} as const;
