export const ROUTES = {
  home: '/',
  movieDetail: (id: string | number) => `/Detail/${id}`,
  cinemaDetail: (id: string | number) => `/Cinema/${id}`,
  register: '/Register',
  login: '/Login',
  verifyCode: '/verifycode',
  profile: '/Profile',
  forgotPassword: '/ForgotPassword',
  resetPassword: '/ResetPassword',
  changePassword: '/ChangePassword',
  userInfo: '/UserInfo',
  cinemaInfo: '/CinemaInfo',
  myBookings: '/MyBookings',
  playing: '/Playing',
  upcoming: '/Upcoming',
  cinemas: '/Cinemas',
  bookSeat: '/BookSeat',
  bookTicket: (id: string | number) => `/BookTicket/${id}`,
  invoice: '/Invoice',
  paymentResult: '/PaymentResult',
  adminMovies: '/Show',
  adminSchedules: '/ShowSchedule',
  adminUsers: '/ShowUser',
  deleteUser: (id: string | number) => `/Delete/${id}`,
  blockUser: (id: string | number) => `/BlockUser/${id}`,
  unblockUser: (id: string | number) => `/UnBlockUser/${id}`,
  adminDashboard: '/AdminDashboard',
  adminCinemas: '/AdminCinemas',
  adminTransactions: '/AdminTransactions',
  adminReviews: '/AdminReviews',
  ownerDashboard: '/OwnerDashboard',
  ownerCinemas: '/OwnerCinemas',
  ownerCinemaRooms: (cinemaId: string | number) => `/OwnerCinemas/${cinemaId}/Rooms`,
  ownerCombos: '/OwnerCombos',
  ownerVouchers: '/OwnerVouchers',
  ownerBookings: '/OwnerBookings',
} as const;
