export const ROUTES = {
  home: '/',
  movieDetail: (id: string | number) => `/Detail/${id}`,
  cinemaDetail: (id: string | number) => `/Cinema/${id}`,
  register: '/Register',
  login: '/Login',
  verifyCode: '/verifycode',
  profile: '/Profile',
  forgotPassword: '/ForgotPassword',
  resetPassword: '/ResetPassword',
  changePassword: '/ChangePassword',
  userInfo: '/UserInfo',
  myBookings: '/MyBookings',
  myTickets: '/MyTickets',
  ticketDetail: (id: string | number) => `/Ticket/${id}`,
  paymentHistory: '/PaymentHistory',
  myRefunds: '/MyRefunds',
  myMembership: '/MyMembership',
  myGiftCards: '/MyGiftCards',
  notifications: '/Notifications',
  playing: '/Playing',
  upcoming: '/Upcoming',
  cinemas: '/Cinemas',
  about: '/About',
  faq: '/FAQ',
  contact: '/Contact',
  bookSeat: '/BookSeat',
  bookTicket: (id: string | number) => `/BookTicket/${id}`,
  invoice: '/Invoice',
  paymentResult: '/PaymentResult',
  adminMovies: '/Show',
  adminSchedules: '/ShowSchedule',
  adminUsers: '/ShowUser',
  deleteUser: (id: string | number) => `/Delete/${id}`,
  blockUser: (id: string | number) => `/BlockUser/${id}`,
  unblockUser: (id: string | number) => `/UnBlockUser/${id}`,
  adminDashboard: '/AdminDashboard',
  adminCinemas: '/AdminCinemas',
  adminTransactions: '/AdminTransactions',
  adminPayments: '/AdminPayments',
  adminReviews: '/AdminReviews',
  ownerDashboard: '/OwnerDashboard',
  ownerCinemas: '/OwnerCinemas',
  ownerCinemaRooms: (branchId: string | number) => `/OwnerCinemas/${branchId}/Rooms`,
  ownerRooms: '/OwnerCinemas/Rooms',
  ownerMaintenance: '/OwnerMaintenance',
  ownerDevices: '/OwnerDevices',
  ownerKiosks: '/OwnerKiosks',
  kiosk: '/kiosk',
  ownerCombos: '/OwnerCombos',
  ownerInventory: '/OwnerInventory',
  ownerVouchers: '/OwnerVouchers',
  ownerGiftCards: '/OwnerGiftCards',
  ownerPromotions: '/OwnerPromotions',
  ownerPricingRules: '/OwnerPricingRules',
  ownerHolidays: '/OwnerHolidays',
  ownerBookings: '/OwnerBookings',
  bookingManagement: '/BookingManagement',
  refundManagement: '/RefundManagement',
  supportTickets: '/SupportTickets',
  auditLog: '/AuditLog',
  notificationTemplates: '/NotificationTemplates',
  systemConfig: '/SystemConfig',
  comboOrders: '/ComboOrders',
  cashierShifts: '/CashierShifts',
  ownerEmployees: '/OwnerEmployees',
  ownerShifts: '/OwnerShifts',
  ownerShiftAssignments: '/OwnerShifts/Assignments',
  adminActors: '/AdminActors',
  adminDirectors: '/AdminDirectors',
  employeeDashboard: '/EmployeeDashboard',
  employeeCounterSale: '/EmployeeCounterSale',
  employeeBoxOffice: '/BoxOffice',
  employeeCheckIn: '/EmployeeCheckIn',
  employeeMySchedule: '/EmployeeMySchedule',
} as const;
